name: survey-dashboard
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.9
  - pip
  - jupyter
  - jupyterlab
  - voila
  - ipywidgets
  - pandas
  - matplotlib
  - numpy
  - openpyxl
  - plotly
